title: SeoJin Jeong | Robotics Portfolio
theme: minima    # <--- 여기를 꼭 minima로 바꾸세요!
description: >-
  Robotics Portfolio - Design, Control Theory, Open Source Projects.
url: "https://jeongseojin.github.io"

header_pages:
  - README.md
  - projects.md
  - about.md

plugins:
  - jekyll-seo-tag
  - jekyll-sitemap